using System;
using System.Threading.Tasks;
using Xunit;
using YouTrackSharp.Issues;
using YouTrackSharp.Tests.Infrastructure;

// ReSharper disable once CheckNamespace
namespace YouTrackSharp.Tests.Integration.Issues
{
    public partial class IssuesServiceTests
    {
        public class DeleteAttachmentForIssue
        {
            [Fact]
            public async Task Valid_Connection_Deletes_Attachment_For_Issue()
            {
                // Arrange
                bool acted = false;
                var connection = Connections.Demo1Token;
                var service = connection.CreateIssuesService();
                
                var issue = new Issue
                {
                    Summary = "Test issue - " + DateTime.UtcNow.ToString("U"),
                    Description = "This is a test issue created while running unit tests."
                };
                
                issue.SetField("State", "Fixed");
                
                var issueId = await service.CreateIssue("DP1", issue);

                for (var i = 1; i <= 3; i++)
                {
                    using (var attachmentStream = await TestUtilities.GenerateAttachmentStream("Generated by unit test."))
                    {
                        await service.AttachFileToIssue(issueId, $"file-{i}.txt", attachmentStream);
                    }
                }
                
                var attachments = await service.GetAttachmentsForIssue(issueId);
                foreach (var attachment in attachments)
                {
                    // Act & Assert
                    await service.DeleteAttachmentForIssue(issueId, attachment.Id);
                    acted = true;
                }

                Assert.True(acted);
            }
        }
    }
}