using System;
using System.Linq;
using System.Threading.Tasks;
using Xunit;
using YouTrackSharp.Issues;
using YouTrackSharp.Tests.Infrastructure;

// ReSharper disable once CheckNamespace
namespace YouTrackSharp.Tests.Integration.Issues
{
    public partial class IssuesServiceTests
    {
        public class GetAttachmentsForIssue
        {
            [Fact]
            public async Task Valid_Connection_Gets_Attachments_For_Issue()
            {
                var connection = Connections.Demo1Token;
                using (var temporaryIssueContext = await TemporaryIssueContext.Create(connection, GetType()))
                {
                    var service = connection.CreateIssuesService();
                
                    for (var i = 1; i <= 3; i++)
                    {
                        using (var attachmentStream = await TestUtilities.GenerateAttachmentStream("Generated by unit test."))
                        {
                            await service.AttachFileToIssue(temporaryIssueContext.Issue.Id, $"file-{i}.txt", attachmentStream);
                        }
                    }
                
                    // Act
                    var attachments = await service.GetAttachmentsForIssue(temporaryIssueContext.Issue.Id);
                
                    // Assert
                    Assert.True(attachments.Count() == 3);

                    await temporaryIssueContext.Destroy();
                }
            }
        }
    }
}